# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Merge"

on:
  push:
    branches: [main, release-*, feature-*]
  # Also allow for manual invocation for testing
  workflow_dispatch:


jobs:
  build:
    if: ${{ github.repository == 'odpi/egeria-connector-integration-topic-strimzi'}}
    runs-on: ubuntu-latest
    name: "Merge"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          # Publishing attributes for maven central (this step adds to setting.xml)
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Keys must be known to maven central - require broad publishing
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # Only for a merge into this repo - not a fork, and just for the main branch
      - name: Build (Publish snapshots to maven central)
        if: ${{ github.repository == 'odpi/egeria-connector-integration-topic-strimzi' && github.ref == 'refs/heads/main'}}
        # TODO: Need to extend build to make use of snapshot repo for publishing
        run: ./gradlew publish
        # Import secrets needed for code signing and distribution
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          # Build and publish - but only for master
      # In other cases just build but don't publish
      - name: Build (no snapshots)
        if: ${{ github.repository != 'odpi/egeria-connector-integration-topic-strimzi' || github.ref != 'refs/heads/main'}}
        run: ./gradlew build
      # --
      - name: Upload Connector
        uses: actions/upload-artifact@v2
        with:
          name: Strimzi Integration Connector
          path: '**/build/libs/*.jar'
